import { useState } from 'react';
import CopyAddressButton from './CopyAddressButton.jsx';
import ExternalLink from './ExternalLink.jsx';

function formatDate(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(date); }
export default function DashboardHeader({ snapshot, onSearch = () => {} }) {
  const [query, setQuery] = useState(''); const mint = snapshot?.mint ?? ''; const solscanUrl = mint ? `https://solscan.io/token/${mint}` : 'https://solscan.io';
  function handleSubmit(event) { event.preventDefault(); onSearch(query.trim()); }
  return <section className="mb-4" aria-labelledby="dashboard-title"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="m-0 text-[10px] text-muted">Holder intelligence / live snapshot</p><h2 id="dashboard-title" className="m-0 mt-1 font-serif text-2xl font-normal text-[#222] sm:text-3xl">rkuSOL Holder &amp; Points</h2><p className="m-0 mt-2 max-w-2xl text-[11px] leading-5 text-muted">Supply, wallets, and estimated points in a quiet, data-first view. Estimates are based on first acquisition and are not official Raiku or Discord figures.</p></div><div className="flex items-center gap-2 text-[10px]"><CopyAddressButton value={mint} /><ExternalLink href={solscanUrl}>Solscan ↗</ExternalLink></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-rule pt-3"><span className="font-mono text-[10px] text-muted">snapshot {formatDate(snapshot?.ts)} · launch {formatDate(snapshot?.stats?.launchDate)}</span><form className="flex min-w-0 gap-2" onSubmit={handleSubmit} role="search"><label className="sr-only" htmlFor="wallet-search-input">Search a wallet</label><input id="wallet-search-input" className="min-w-0 flex-1 border border-rule bg-surface px-3 py-1.5 text-[11px] outline-none placeholder:text-[#999] focus:ring-2 focus:ring-accent sm:w-72" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search wallet address" /><button className="h-7 border border-[#1b1b1b] bg-[#1b1b1b] px-3 text-[10px] font-medium text-white hover:opacity-90" type="submit">Search</button></form></div></section>;
}
